# Generated by Django 4.1.5 on 2023-01-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dipartment', models.CharField(max_length=50)),
                ('experience', models.ImageField(max_length=50, upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
