# Generated by Django 4.1.5 on 2023-01-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(max_length=50),
        ),
    ]
